# Generated by Django 4.2.4 on 2023-11-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primaryKey', models.CharField(max_length=255)),
                ('csId', models.CharField(max_length=10)),
                ('customerId', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('expiredAt', models.BigIntegerField()),
                ('orderDate', models.BigIntegerField()),
                ('paymentRequestId', models.CharField(max_length=50)),
                ('socketId', models.CharField(max_length=10)),
                ('status', models.IntegerField()),
                ('totalPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='chargingstationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primaryKey', models.CharField(max_length=255)),
                ('csId', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=255)),
                ('idMitra', models.CharField(max_length=255)),
                ('kabupaten', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('longt', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('provinsi', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='customersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primaryKey', models.CharField(max_length=255)),
                ('fcmToken', models.CharField(max_length=255)),
                ('bookActive', models.CharField(max_length=5)),
                ('customerId', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='mitraData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primaryKey', models.CharField(max_length=255)),
                ('fcmToken', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('nama', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=20)),
            ],
        ),
    ]
